/**
 * This class is generated by jOOQ
 */
package com.main.jooq.model;


import com.main.jooq.model.tables.FlywaySchemaHistory;
import com.main.jooq.model.tables.Orders;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in store
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>store.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.main.jooq.model.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>store.orders</code>.
     */
    public static final Orders ORDERS = com.main.jooq.model.tables.Orders.ORDERS;
}
